#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[3]
LANE_DIR = Path(__file__).resolve().parent
PREPARE_MEDIA = LANE_DIR / 'prepare_capture_media.py'
REPORT_READINESS = LANE_DIR / 'report_capture_readiness.py'
EMIT_RUNBOOK = LANE_DIR / 'emit_capture_runbook.py'
SERIAL_LOG_DIR = LANE_DIR / 'out' / 'serial-logs'
VARIANTS = [
    'running-live-install',
    'outdated-running-iso-upgrade',
    'outdated-running-source-device-upgrade',
]


def run_json(command: list[str]) -> dict[str, Any]:
    result = subprocess.run(command, check=False, text=True, capture_output=True)
    try:
        payload = json.loads(result.stdout or '{}')
    except json.JSONDecodeError as error:
        raise SystemExit(f"command produced invalid JSON: {' '.join(command)}\n{error}\nstdout={result.stdout}\nstderr={result.stderr}") from error
    if result.returncode != 0:
        raise SystemExit(f"command failed: {' '.join(command)}\nstdout={result.stdout}\nstderr={result.stderr}")
    return payload


def role_args(roles: dict[str, str]) -> list[str]:
    args: list[str] = []
    for role, value in sorted(roles.items()):
        args.extend(['--role', f'{role}={value}'])
    return args


def prepare_media(output_dir: Path | None, force: bool) -> dict[str, Any]:
    command = ['python3', str(PREPARE_MEDIA)]
    if output_dir is not None:
        command.extend(['--output-dir', str(output_dir)])
    if force:
        command.append('--force')
    return run_json(command)


def readiness(roles: dict[str, str]) -> dict[str, Any]:
    command = ['python3', str(REPORT_READINESS), '--require-existing-media', '--json', *role_args(roles)]
    return run_json(command)


def emit_runbook(variant: str, roles: dict[str, str], output_dir: Path | None) -> dict[str, Any]:
    command = ['python3', str(EMIT_RUNBOOK), '--variant', variant, '--require-existing-media', *role_args(roles)]
    if output_dir is not None:
        command.extend(['--output-dir', str(output_dir)])
    return run_json(command)


def write_operator_readme(runbooks: dict[str, dict[str, Any]], output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / 'README.md'
    lines = [
        '# Real-boot capture runbooks',
        '',
        'Generated by `prepare_all_capture_runbooks.py`.',
        '',
        '## Runtime sequence',
        '',
        'For each variant:',
        '',
        '1. Run `<variant>.sh print` and read the commands.',
        '2. Run `<variant>.sh capture` to boot QEMU and wait for the serial marker.',
        '3. Paste the printed guest command inside the booted Tails guest.',
        '4. Run `<variant>.sh record` after the marker is captured.',
        '',
        '## Variants',
        '',
    ]
    for variant in VARIANTS:
        runbook = Path(runbooks[variant]['runbook'])
        rel_runbook = runbook if not runbook.is_absolute() else runbook
        lines.extend(
            [
                f'### {variant}',
                '',
                f'Runbook: `{rel_runbook}`',
                '',
                '```bash',
                f'{runbook} print',
                f'{runbook} capture',
                '# paste the printed guest command inside Tails',
                f'{runbook} record',
                '```',
                '',
            ]
        )
    path.write_text('\n'.join(lines), encoding='utf-8')
    return path


def prepare_all(*, media_dir: Path | None, runbook_dir: Path | None, force: bool) -> dict[str, Any]:
    SERIAL_LOG_DIR.mkdir(parents=True, exist_ok=True)
    media = prepare_media(media_dir, force=force)
    roles = media['roles']
    report = readiness(roles)
    if report['ready_count'] != report['total_count']:
        raise SystemExit(json.dumps({'success': False, 'media': media, 'readiness': report}, indent=2, sort_keys=True))
    runbooks = {variant: emit_runbook(variant, roles, runbook_dir) for variant in VARIANTS}
    readme_dir = runbook_dir or Path(runbooks[VARIANTS[0]]['runbook']).parent
    readme = write_operator_readme(runbooks, readme_dir)
    return {
        'success': True,
        'media': media,
        'readiness': report,
        'runbooks': runbooks,
        'operator_readme': str(readme),
        'serial_log_dir': str(SERIAL_LOG_DIR),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description='Prepare media, verify readiness, and emit all real-boot capture runbooks.')
    parser.add_argument('--media-dir', type=Path)
    parser.add_argument('--runbook-dir', type=Path)
    parser.add_argument('--force', action='store_true')
    args = parser.parse_args()
    print(json.dumps(prepare_all(media_dir=args.media_dir, runbook_dir=args.runbook_dir, force=args.force), indent=2, sort_keys=True))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
